### ISSUE TITLE
Switch package manager from npm to yarn

### ISSUE THREAD

**Issue by cgcardona** [ava-labs/avalanchejs#269]
[yarn](https://yarnpkg.com) is a more modern package manager than [npm](https://www.npmjs.com). In order to switch to `npm` to `yarn` we need to update the continuous integration workflow. You also need to

* Update CI
* Remove package-lock and replace w/ yarn lock
* Update gitignore

## Example `ci.yml`

Replace the following: 

```yml
          cache: npm
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
```

With this updated yml

```yml
          cache: yarn
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn test
```
